#!/bin/bash
cd /home/debian/jugglingpatterns-wiki/jugglingpatterns-wiki
git add --dry-run images
echo doing rsync
sleep 2;
rsync -va /var/lib/mediawiki/images/[1-9a-z]/ images/
git add --dry-run images
ls -la /var/lib/automysqlbackup/daily/my_jugglingwiki/*sql
su -c "zcat /var/lib/automysqlbackup/daily/my_jugglingwiki/my_jugglingwiki_$(date --iso)*gz" | sed  's/\(:sha512:[0-9]*:[0-9]*:\)[^:]*:[^,]*/\1:XXX:XXX/;s/iridos*@gmail.com/mail/' > /home/debian/jugglingpatterns-wiki/jugglingwiki.sql
git add images jugglingwiki.sql

