#!/bin/bash
#cd /home/debian/jugglingpatterns-wiki/
gitdir=/root/jugglingpatterns-wiki/
cd $gitdir
su -c "chmod a+rX /var/lib/mediawiki/images/"
git add --dry-run images
echo doing rsync
sleep 2;
rsync -va /var/lib/mediawiki/images/[1-9a-z]/ images/
git add --dry-run images
ls -la /var/lib/automysqlbackup/daily/my_jugglingwiki/*$(date --iso)*sql.gz # this seems to have changed to have gz of current day from around midnight
su -c "zcat /var/lib/automysqlbackup/daily/my_jugglingwiki/my_jugglingwiki_$(date --iso)*gz" | sed  's/\(:sha512:[0-9]*:[0-9]*:\)[^:]*:[^,]*/\1:XXX:XXX'\''/;s/iridos*@gmail.com/mail/' > jugglingwiki.sql
rsync -v /var/www/jugglingpatterns/animation.html var_www_html
rsync -v -L /var/www/jugglingpatterns/js/animation-widget-standalone.mjs var_www_html
rsync -v -L /var/www/jugglingpatterns/js/animation-widget-standalone.mjs.map var_www_html

# remove wiki secrets before commit
awk '/wgDBpassword|wgSecretKey|wgUpgradeKey/{gsub("\".*\"","\"\"");}{print}' /etc/mediawiki/LocalSettings.php > etc_LocalSettings.php

# no secrets in this file as far as I can see
cp /etc/apache2/sites-enabled/jugglingpatterns.conf etc_apache2_sites-enabled_jugglingpatterns.conf

git add images jugglingwiki.sql var_www_html etc_LocalSettings.php etc_apache2_sites-enabled_jugglingpatterns.conf prepare_git
git commit
# use custom deploy key
GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_jugglingpatternsgit" git push
